######################################################################
# Automatically generated by qmake (2.00a) Sun Aug 13 18:21:39 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . ../audio/libaudio.a
INCLUDEPATH += . ../audio /usr/local/include/SDL
LIBS += ../audio/libaudio.a
CONFIG += link_prl

# Input
SOURCES += main.cc
