#!/usr/bin/perl -w

if (!defined($ARGV[0]) || ($ARGV[0] eq '--help')) {
	print "Usage: svnversion.pl /path/to/svnversion.h\n";
	exit 1;
}

use strict;
use warnings;

my $header = $ARGV[0];
my $REV = `svnversion -n .`;

open(FH, ">$header");
print FH <<EOF
#ifndef _SVNVERSION_H
#define _SVNVERSION_H
// Automatically generated by svnversion.pl
// DO NOT EDIT - YOUR CHANGES WILL BE LOST!
#define SIGTERM_VERSION_SVNREVISION "$REV"
#endif
EOF
;
close(FH);

print "       >> Subversion Revision: $REV\n";

